# Generated by Django 2.1.8 on 2019-11-16 10:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goods_type',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AddField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=50, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(upload_to='media/image', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(blank=True, null='True', verbose_name='价钱'),
        ),
        migrations.AlterField(
            model_name='type',
            name='Type_name',
            field=models.CharField(max_length=50, verbose_name='类型'),
        ),
    ]
