# Generated by Django 2.1.8 on 2019-11-16 11:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_auto_20191116_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('image', models.ImageField(upload_to='media/news/image/', verbose_name='新闻图片')),
                ('date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('description', ckeditor.fields.RichTextField(default='', verbose_name='新闻详情')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
